#    ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀░█▀▀
#    ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀░▀▀█
#    ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀

windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#Pavucontrol
windowrule = match:class org.pulseaudio.pavucontrol, size 750 500, float on

#Mission Center
windowrule = match:class net.nokyan.Resources, size 961 682, float on

#Kitty
windowrule = no_blur on, match:class kitty

#Picture-in-Picture
windowrule = match:title Picture-in-Picture, move (monitor_w-605) (monitor_h-340), float on, pin on, opaque on
